### ISSUE TITLE
Version 1.7.2 is missing on packagist

### ISSUE THREAD

**Issue by thasmo** [bitmotion/static-info-tables-cs#3]
Seems like version `1.7.2` has been released but is not available on packagist. Did you forget to push tags or something? Would be awesome to have `1.7.2` on packagist, `1.7.1` throws an exception which was fixed in 1e5780f93ce2e5b465653f7656b124fa72b534bb.

**Comment by bmafeldt** [comment]
Hi thasmo,
we've released a new version 6.7.3. which is available on TER and packagist. This should also fix the issue #4.
